

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/imenpfe
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
  servlet:
     multipart:
         max-file-size: 100MB
         max-request-size: 100MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: elmorched.91n@gmail.com
    password: mpbz szie qljw yemo
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
